using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using SpatialSys.UnitySDK;

public class MinimapFollow : MonoBehaviour
{
    private IAvatar localAvatar;
    //private ICameraService cameraService;
    void Start()
    {
        localAvatar = SpatialBridge.actorService.localActor.avatar;
        //cameraService = SpatialBridge.cameraService;
    }

    void Update()
    {
        localAvatar = SpatialBridge.actorService.localActor.avatar;
        Vector3 newPosition = localAvatar.position;
        newPosition.y = transform.position.y;
        transform.position = newPosition;
        //transform.rotation = Quaternion.Euler(90f, cameraService.rotation.eulerAngles.y, 90f);
    }
}